### ISSUE TITLE
Replace whitelist with different name

### ISSUE THREAD

**Issue by mvz** [mvz/non-digest-assets#41]
Let's replace whitelist ~and blacklist~ with different names.

To make this a smooth transition, this involves multiple steps:

- [x] Pick good replacement name~s~
- [x] Implement new name~s~
- [x] Deprecate old name~s~
- [x] Release minor version
- [x] Remove old name~s~
- [x] Release major version

**Comment by mvz** [comment]
It looks like only whitelist is used, actually. So we need only one replacement name.

**Comment by mvz** [comment]
I'm going with `selected_assets` for now. This can still be changed up until a release is made.

**Comment by mvz** [comment]
I finally settled on `asset_selectors` since the list can also contain regular expressions.
